import { describe, expect, it } from "vitest";
import { killsByPattern, PATTERN_KILL_REASON } from "../src/core/pattern-kill.js";

// smarty-dev#774: the three real incidents verbatim, then the forms the rule refuses and the
// reads and recorded-PID kills it must still allow.
const refused: Array<[string, string]> = [
  ["incident 09-25 14:05Z: the Lucky stub test on Dev1", `pkill -f '[w]atch'`],
  ["incident 09-26 03:05Z: over ssh on m4max", `ssh m4max "pkill -f 'sleep 30' -P 1"`],
  ["incident 09-26 03:05Z: the command itself", `pkill -f 'sleep 30' -P 1`],
  ["incident 09-27 ~23:2xZ: dev-lead's own shell", `pkill -f "retry418.sh"`],
  ["incident 09-27, unquoted", `pkill -f retry418.sh`],
  ["dev-lead's earlier slip", `cd /tmp; pkill -f retry226.sh; nohup ./retry226.sh > /tmp/retry226.log 2>&1 &`],
  ["a pkill after a cat", `cat /tmp/retry278.log; pkill -f "^/bin/bash ./retry278.sh" 2>/dev/null`],
  ["killall", `killall node`],
  ["a pkill by path", `/usr/bin/pkill -U paul sleep`],
  ["a pkill behind sudo and timeout", `sudo timeout 5 pkill -9 vitest`],
  ["a pkill behind env", `env -u GH_TOKEN FOO=1 pkill -f watcher`],
  ["a pkill after &&", `make build && pkill -f server`],
  ["a pkill in a pipeline's last stage", `echo x | pkill -f y`],
  ["a pkill on the next line", `echo start\npkill -f x`],
  ["a pkill after a backslash continuation", `sleep 1 && \\\n  pkill -f x`],
  ["kill $(pgrep …)", `kill $(pgrep -f retry418.sh)`],
  ["kill -9 $(pgrep …)", `kill -9 $(pgrep -f vitest)`],
  ["kill \`pgrep …\`", "kill `pgrep -f server`"],
  ["kill \"$(pgrep …)\"", `kill "$(pgrep -f server)"`],
  ["kill $(pidof …)", `kill $(pidof node)`],
  ["kill $(ps | grep | awk)", `kill $(ps aux | grep '[s]erver' | awk '{print $2}')`],
  ["pgrep | xargs kill", `pgrep -f watch | xargs kill`],
  ["pgrep | xargs -r kill -9", `pgrep -f watch | xargs -r kill -9`],
  ["pgrep |\\n xargs kill", `pgrep -f watch |\n  xargs kill`],
  ["ps | grep | awk | xargs kill", `ps aux | grep '[w]atch' | awk '{print $2}' | xargs kill`],
  ["a captured PID list", `P=$(pgrep -f server); kill $P`],
  ["a for loop over pgrep", `for p in $(pgrep -f server); do kill "$p"; done`],
  ["a while loop fed by pgrep", `pgrep -f server | while read p; do kill $p; done`],
  // Security N5 on pi-fabric#148: the same lookup fed through a redirect.
  ["a while loop fed by a pgrep process substitution", `while read p; do kill "$p"; done < <(pgrep x)`],
  ["xargs kill fed by a pgrep here-string", `xargs kill <<< "$(pgrep x)"`],
  // Round 3 security N8 on #148: a compound producer's lookup survives the closing group/loop.
  ["N8: a brace group lookup feeds xargs kill", `{ pgrep x; } | xargs kill`],
  ["N8: a subshell lookup feeds xargs kill", `(pgrep x) | xargs kill`],
  ["N8: a loop lookup feeds xargs kill", `for name in worker server; do pgrep -f "$name"; done | xargs kill`],
  ["N8: a brace group lookup feeds read then kill", `{ pgrep x; } | while read -r p; do kill "$p"; done`],
  ["N8: a subshell lookup feeds read then kill", `(pgrep x) | while read -r p; do kill "$p"; done`],
  ["N8: a loop lookup feeds read then kill", `for name in worker server; do pgrep -f "$name"; done | while read -r p; do kill "$p"; done`],
  ["bash -c 'pkill …'", `bash -c 'pkill -f server'`],
  ["bash -lc 'kill $(pgrep …)'", `bash -lc 'kill $(pgrep -f server)'`],
  ["sh -c with pgrep | xargs kill", `sh -c "pgrep -f x | xargs kill"`],
  ["ssh HOST 'kill $(pgrep …)'", `ssh -p 22 m4max 'kill $(pgrep -f "sleep 30")'`],
  ["ssh HOST 'pgrep … | xargs kill'", `ssh m4max 'pgrep -f sleep | xargs kill'`],
  ["ssh HOST bash -c '…'", `ssh m4max bash -c "'pkill -f sleep'"`],
  ["ssh pgrep piped into a local xargs kill", `ssh m4max pgrep -f sleep | xargs kill`],
  ["a heredoc script fed to ssh", `ssh m4max <<'EOF'\ncd /tmp\npkill -f sleep\nEOF`],
  ["a heredoc script fed to bash", `bash <<EOF\nkillall node\nEOF`],
  ["eval", `eval "pkill -f server"`],
  ["a pkill in a command substitution", `echo "$(pkill -f server)"`],
  ["a pkill in a subshell", `(cd /tmp && pkill -f x)`],
  ["a pkill in an if", `if true; then pkill -f x; fi`],
  // review/astra F1 on #105: a lookup expanded into the script a shell, eval or ssh runs.
  ["bash -c \"kill $(pgrep …)\"", `bash -c "kill $(pgrep -f worker)"`],
  ["eval \"kill $(pgrep …)\"", `eval "kill $(pgrep -f worker)"`],
  ["ssh HOST \"kill $(pgrep …)\"", `ssh HOST "kill $(pgrep -f worker)"`],
  ["ssh HOST kill $(pgrep …), unquoted", `ssh HOST kill $(pgrep -f worker)`],
  ["ssh HOST \"kill `pgrep …`\"", "ssh HOST \"kill `pgrep -f worker`\""],
  // review/astra F2 on #105: substitutions in a redirection target and an unquoted heredoc run.
  ["a redirection target", `: >"$(pkill -f worker)"`],
  ["an unquoted redirection target", `echo x > $(pkill -f worker).log`],
  ["single quotes in an unquoted heredoc", `cat <<EOF\n'$(pkill -f worker)'\nEOF`],
  ["a # line in an unquoted heredoc", `cat <<EOF\n# $(pkill -f worker)\nEOF`],
  ["a backtick in an unquoted heredoc", "cat <<EOF\nnote `pkill -f worker`\nEOF"],
  ["a lookup kill in an unquoted heredoc", `cat <<EOF\nstopped: $(kill $(pgrep -f worker))\nEOF`],
  // review/astra F3 on #105: a leading redirection and long or clustered wrapper options.
  ["a leading 2> redirection", `2>/dev/null pkill -f worker`],
  ["a leading >file redirection", `>out.log pkill -f worker`],
  ["sudo --user X", `sudo --user paul pkill -f worker`],
  ["sudo -Eu X", `sudo -Eu paul pkill -f worker`],
  ["env --unset X", `env --unset GH_TOKEN pkill -f worker`],
  ["env --unset=X", `env --unset=GH_TOKEN pkill -f worker`],
  ["env -S 'pkill …'", `env -S 'pkill -f worker'`],
  ["nice -n 5", `nice -n 5 pkill -f worker`],
  ["timeout 5", `timeout 5 pkill -f worker`],
  ["timeout --signal KILL 5", `timeout --signal KILL 5 pkill -f worker`],
  ["nohup", `nohup pkill -f worker &`],
  ["setsid", `setsid pkill -f worker`],
  ["command", `command pkill -f worker`],
  ["exec", `exec pkill -f worker`],
  ["xargs -r kill", `pgrep -f worker | xargs -r kill`],
  ["xargs --max-args 1 kill", `pgrep -f worker | xargs --max-args 1 kill -TERM`],
  ["a lookup kill with a trailing redirection", `kill $(pgrep -f worker) 2>/dev/null`],
  // review/astra F4 on #105: an attached short-option value.
  ["sudo -uroot", `sudo -uroot pkill -f worker`],
  ["sudo --user=root", `sudo --user=root pkill -f worker`],
  // review/astra F5 on #105: lookup output carried into a variable, a wrapper, or a quoted PID.
  ["p=$(pgrep x); kill $p", `p=$(pgrep x); kill $p`],
  ["p=$(pgrep x); kill -9 \"\${p}\"", `p=$(pgrep x); kill -9 "\${p}"`],
  ["a captured lookup, then bash -c", `P=$(pgrep -f worker); bash -c "kill $P"`],
  ["a captured lookup, then eval", `P=$(pgrep -f worker); eval "kill $P"`],
  ["a captured lookup, then ssh", `P=$(pgrep -f worker); ssh HOST "kill $P"`],
  ["a captured lookup inside bash -c", `bash -c 'p=$(pgrep x); kill $p'`],
  ["a captured lookup inside eval", `eval 'p=$(pgrep x); kill $p'`],
  ["a quoted expanded PID in bash -c", `bash -c "kill '$(pgrep -f worker)'"`],
  ["a PGID read by ps", `PGID=$(ps -o pgid= -p "$PID" | tr -d ' '); kill -TERM -- -$PGID`],
  ["ps piped into xargs kill", `ps -o pid= -p "$PID" | xargs kill`],
  ["a PID list from grep alone", `kill $(grep -l worker /proc/*/cmdline | cut -d/ -f3)`],
  ["a captured lookup killed in a substitution", `P=$(pgrep -f worker); echo "$(kill $P)"`],
  // review/astra F6 on #105: lookups expanded into an env -S script or a heredoc script.
  ["env -S \"kill $(pgrep …)\"", `env -S "kill $(pgrep -f worker)"`],
  ["env --split-string \"kill $(pgrep …)\"", `env --split-string "kill $(pgrep -f worker)"`],
  ["env --split-string=\"kill $(pgrep …)\"", `env --split-string="kill $(pgrep -f worker)"`],
  ["an unquoted heredoc to bash with a quoted lookup", `bash <<EOF\nkill '$(pgrep -f worker)'\nEOF`],
  ["an unquoted heredoc to ssh with a quoted lookup", `ssh HOST <<EOF\nkill '$(pgrep -f worker)'\nEOF`],
  // review/astra F7 on #105: env's split string in a short cluster.
  ["env -iS 'pkill …'", `env -iS 'pkill -f worker'`],
  ["env -iS'pkill …'", `env -iS'pkill -f worker'`],
  // review/astra F8 on #105: provenance per operand inside a heredoc or -c script.
  ["a heredoc diagnostic, then a lookup kill", `bash <<EOF\necho "workers: $(pgrep -c worker)"\nkill $(pgrep -f worker)\nEOF`],
  ["a captured lookup killed inside a heredoc", `bash <<'EOF'\np=$(pgrep x); kill $p\nEOF`],
  ["a captured lookup killed inside an unquoted heredoc", `bash <<EOF\np=\\$(pgrep x); kill \\$p\nEOF`],
  ["a bash -c diagnostic, then a lookup kill", `bash -c "echo $(pgrep -c worker); kill $(pgrep -f worker)"`],
  // review/astra F9 on #105: positional parameters after -c, and xargs input.
  ["bash -c 'kill \"$1\"' _ \"$(pgrep …)\"", `bash -c 'kill "$1"' _ "$(pgrep -f worker)"`],
  ["bash -c 'kill \"$@\"' _ $(pgrep …)", `bash -c 'kill "$@"' _ $(pgrep -f worker)`],
  ["sh -c 'kill $0' $(pgrep …)", `sh -c 'kill $0' $(pgrep -f worker)`],
  ["a captured lookup passed as $1", `P=$(pgrep -f worker); bash -c 'kill "$1"' _ "$P"`],
  ["pgrep | xargs sh -c 'kill \"$@\"' _", `pgrep x | xargs sh -c 'kill "$@"' _`],
  ["pgrep | xargs -r sh -c 'kill \"$@\"' _", `pgrep -f worker | xargs -r sh -c 'kill "$@"' _`],
  ["pgrep | xargs -I{} sh -c 'kill {}'", `pgrep -f worker | xargs -I{} sh -c 'kill {}'`],
  ["a grep-selected PID", `kill $(ps aux | grep '[w]orker' | awk '{print $2}')`],
];

const allowed: Array<[string, string]> = [
  ["a string that mentions pkill", `echo "never use pkill"`],
  ["a grep for pkill", `grep -rn pkill src/ docs/`],
  ["a grep for kill $(pgrep", `grep -rn 'kill $(pgrep' .`],
  ["dev-lead's note that quotes the incident",
    `P=~/.local/state/dev-lead-posts; printf -- '- %s NOTE: I ran pkill -f "retry418.sh" (name pattern, against #774)\\n' "$(date -u +%H:%MZ)" >> "$P/notes.md"`],
  ["a heredoc body that describes the incident",
    `cat > /tmp/incident.md <<'EOF'\n**What ran.** lucky-sweep ran this on m4max:\n\`\`\`\npkill -f 'sleep 30' -P 1\n\`\`\`\nEOF`],
  ["a gh api comment that names the forms",
    `gh api repos/o/r/issues/774/comments -f body='Refused: pkill, killall, kill $(pgrep x), pgrep x | xargs kill'`],
  ["a commit message", `git commit -m "fix: refuse pkill and kill \\$(pgrep)"`],
  ["kill with literal PIDs", `kill 12345 12346`],
  ["kill -TERM of a process group", `kill -TERM -- -4242`],
  ["kill %job", `sleep 100 & kill %1`],
  ["kill -0", `kill -0 12345 && echo alive`],
  ["kill -0 of a looked-up PID", `kill -0 $(pgrep -f server)`],
  ["a recorded PID from $!", `./server & PID=$!; sleep 2; kill "$PID"`],
  ["a recorded PID from a file", `kill $(cat /tmp/x/server.pid)`],
  ["a recorded PID with a redirect", `kill "$PID" 2>/dev/null || true`],
  ["pgrep alone", `pgrep -fl vitest`],
  ["pgrep -c", `pgrep -f 'retry22[678]' -c`],
  ["pgrep in a while wait", `while pgrep -f build >/dev/null; do sleep 1; done`],
  ["a check after a recorded kill", `kill $PID; sleep 1; pgrep -f server || echo gone`],
  ["a ps check before a group kill", `ps -o pid,ppid,pgid,command -p $PID; kill -- -$PGID`],
  ["a ps | grep check before a recorded kill", `ps -eo pid,pgid,args | grep server; kill -- -$PGID`],
  ["smarty-reap stop", `bin/smarty-reap stop .local/reap/server.json`],
  ["smarty-reap run", `bin/smarty-reap run .local/reap/server.json -- ./server --port 8080`],
  ["ssh with a literal kill", `ssh m4max 'kill 4242'`],
  ["ssh pgrep alone", `ssh m4max "pgrep -fl 'sleep 30'"`],
  ["bash -c echo pkill", `bash -c 'echo pkill is refused'`],
  ["a comment that mentions pkill", `ls # never pkill here`],
  ["a word that contains pkill", `./pkill-guard-test.sh --dry-run`],
  ["a file named pkill", `cat docs/pkill.md`],
  ["a literal kill after a captured lookup", `P=$(pgrep -f server); kill 4242`],
  ["a comment that holds a pkill after ;", `ls # do not run: sleep 1; pkill -f x`],
  ["pgrep, then a recorded kill on the next line", `pgrep -fl server\nkill "$PID"`],
  // Counterexamples for review/astra on #105.
  ["pgrep piped into a literal kill", `pgrep -f worker | kill 4242`],
  ["pgrep, then a PID file into xargs kill on the next line", `pgrep -fl worker\ncat run.pid | xargs kill`],
  ["env -S with a literal PID", `env -S "kill 4242"`],
  ["env -S with a PID file", `env -S "kill $(cat run.pid)"`],
  ["env -iS with a literal PID", `env -iS 'kill 4242'`],
  ["env -i with another command", `env -i PATH=/usr/bin ls -l`],
  ["an unquoted heredoc to bash with a PID file", `bash <<EOF\nkill '$(cat run.pid)'\nEOF`],
  ["an unquoted heredoc to bash with a literal PID", `bash <<EOF\nkill 4242\nEOF`],
  ["a quoted-delimiter heredoc to bash with a quoted lookup (inert)", `bash <<'EOF'\nkill '$(pgrep -f worker)'\nEOF`],
  ["a quoted-delimiter heredoc note to cat", `cat <<'EOF'\nkill '$(pgrep -f worker)'\nEOF`],
  ["a lookup expanded into a heredoc to cat", `cat <<EOF > note.md\nworkers: '$(pgrep -f worker)'\nEOF`],
  // Counterexamples for F8 and F9.
  ["a heredoc diagnostic, then a PID-file kill", `bash <<EOF\necho "workers: $(pgrep -c worker)"\nkill $(cat run.pid)\nEOF`],
  ["a bash -c diagnostic, then a PID-file kill", `bash -c "echo $(pgrep -c worker); kill $(cat run.pid)"`],
  ["bash -c 'kill \"$1\"' _ 12345", `bash -c 'kill "$1"' _ 12345`],
  ["bash -c with a lookup in another positional", `bash -c 'kill "$1"; echo "$2"' _ 12345 "$(pgrep -c worker)"`],
  ["xargs -a run.pids sh -c 'kill \"$@\"' _", `xargs -a run.pids sh -c 'kill "$@"' _`],
  ["cat run.pids | xargs sh -c 'kill \"$@\"' _", `cat run.pids | xargs sh -c 'kill "$@"' _`],
  ["kill $(cat run.pid)", `kill $(cat run.pid)`],
  ["kill $(< run.pid)", `kill $(< run.pid)`],
  ["kill -9 $PID", `kill -9 $PID`],
  ["kill -9 12345", `kill -9 12345`],
  ["sudo -uroot kill of a literal PID", `sudo -uroot kill 4242`],
  ["sudo --user=root kill of a literal PID", `sudo --user=root kill 4242`],
  ["a recorded PID in bash -c", `PID=$!; bash -c "kill $PID"`],
  ["a PID file piped into xargs kill", `cat run.pid | xargs kill`],
  // N8 counterparts: grouping recorded PID files does not turn them into process-name lookups.
  ["N8: a brace group of recorded PID files feeds xargs kill", `{ cat .local/server.pid; cat .local/worker.pid; } | xargs kill`],
  ["N8: a subshell with a recorded PID file feeds xargs kill", `(cat .local/server.pid) | xargs kill`],
  ["N8: a loop of recorded PID files feeds xargs kill", `for file in .local/server.pid .local/worker.pid; do cat "$file"; done | xargs kill`],
  ["N8: a brace group of recorded PID files feeds read then kill", `{ cat .local/server.pid; cat .local/worker.pid; } | while read -r p; do kill "$p"; done`],
  ["N8: a subshell with a recorded PID file feeds read then kill", `(cat .local/server.pid) | while read -r p; do kill "$p"; done`],
  ["N8: a loop of recorded PID files feeds read then kill", `for file in .local/server.pid .local/worker.pid; do cat "$file"; done | while read -r p; do kill "$p"; done`],
  ["a pgrep count, then a recorded kill", `N=$(pgrep -c worker); kill "$PID"`],
  ["bash -c \"kill $PID\"", `bash -c "kill $PID"`],
  ["bash -c echo of a lookup", `bash -c 'echo "kill $(pgrep x) is refused"'`],
  ["eval \"kill $PID\"", `eval "kill $PID"`],
  ["ssh HOST kill of a recorded PID file", `ssh HOST "kill $(cat /tmp/w/worker.pid)"`],
  ["a redirection target with date", `: >"$(date +%s).log"`],
  ["a quoted heredoc with a substitution", `cat <<'EOF'\n'$(pkill -f worker)'\nEOF`],
  ["an unquoted heredoc that names pkill", `cat <<EOF\nnever run pkill -f worker ($(date -u +%H:%MZ))\nEOF`],
  ["a leading 2> on pgrep", `2>/dev/null pgrep -f worker`],
  ["sudo --user X kill of a literal PID", `sudo --user paul kill 4242`],
  ["env --unset X grep pkill", `env --unset GH_TOKEN grep -n pkill notes.md`],
  ["command -v pkill", `command -v pkill`],
  ["nohup with redirections", `nohup ./server > server.log 2>&1 &`],
  ["a vitest filter", `./node_modules/.bin/vitest run tests/pattern-kill.test.ts -t pkill`],
];

describe("pattern-kill guard (smarty-dev#774)", () => {
  it.each(refused)("refuses %s", (_label, command) => {
    expect(killsByPattern(command)).toBe(true);
  });

  it.each(allowed)("allows %s", (_label, command) => {
    expect(killsByPattern(command)).toBe(false);
  });

  it("names the fix in its reason", () => {
    expect(PATTERN_KILL_REASON).toMatch(/bin\/smarty-reap stop/);
    expect(PATTERN_KILL_REASON).toMatch(/kill <PID>/);
  });
});
