import {describe,it,expect} from 'vitest';
import {scanCommand,killsByPattern,wipesTmp} from '../src/core/pattern-kill.js';
// Every shell string is inert scanner DATA, never executed.
const SAFE={blocked:false,wipe:false,exhausted:false};const STATE={...SAFE,shellState:true};const TMP={...SAFE,wipe:true};const PID={...SAFE,blocked:true};
function check(command:string,expected:typeof SAFE|typeof STATE):void{const actual=scanCommand(command);expect(actual,command).toStrictEqual(expected);expect(Object.keys(actual).sort(),command).toStrictEqual(Object.keys(expected).sort());expect(actual.exhausted,command).toBe(false);expect(killsByPattern(command),command).toBe(expected.blocked||'shellState'in expected);expect(wipesTmp(command),command).toBe(expected.wipe||'shellState'in expected);}
const continuation='\\\n';
describe('PR166 R13 convergence execution/output admission',()=>{
 const expansions=[`rm -rf $${continuation}'/tmp'`,`rm -rf $${continuation}"/tmp"`,`kill "$${continuation}(pgrep worker)"`,`D=/tmp; : $(${continuation}(D=7)); rm -rf "$D"`,`P=$(pgrep worker); : $${continuation}((P=4242)); kill "$P"`];
 expansions.forEach((command,i)=>{it(`F42-R${i+1} refuses continuation-composed live expansion`,()=>check(command,STATE));it(`F42-SIMPLE${i+1} preserves ordinary continuations and inert dollar data`,()=>{check(`D=/o${continuation}wn; rm -rf "$D"`,SAFE);check(`: '$${continuation}(pgrep worker)'; kill 4242`,SAFE);check(`printf '%s' '$${continuation}((D=7))'; D=/own; rm -rf "$D"`,SAFE);});});
 ['/', '/own/', '""'].forEach((receiver,i)=>{it(`F43-R${i+1} refuses present odd receiver not assignment-only`,()=>{check(`D=/tmp; D=/own ${receiver}; rm -rf "$D"`,STATE);check(`P=$(pgrep worker); P=4242 ${receiver}; kill "$P"`,STATE);});it(`F43-SIMPLE${i+1} real assignment-only and child-prefix lifetimes remain`,()=>{check('D=/tmp; D=/own; rm -rf "$D"',SAFE);check('P=$(pgrep worker); P=4242; kill "$P"',SAFE);check('D=/own; D=/elsewhere /usr/bin/true; rm -rf "$D"',SAFE);});});
 it('F44-R diagnostic set output capture saved and forwarded cannot attest safe bytes',()=>{check("S=$(D='left /tmp right'; set); rm -rf $S",TMP);check("S=$(D='left /tmp right'; set); printf %s \"$S\" > /own/diagnostic; D=$(cat /own/diagnostic); rm -rf $D",TMP);check("S=$(D='left /tmp right'; set); printf %s \"$S\" | xargs rm -rf",TMP);check('P=$(set); kill "$P"',PID);});
 it('F44-SIMPLE diagnostic leaf and genuinely silent positional forms remain',()=>{check('set; kill 4242',SAFE);check('P=$(set -- 4242; printf %s 4242); kill "$P"',SAFE);check('D=$(set -- /own; printf %s /own); rm -rf "$D"',SAFE);});
 const invalid=['pushd -Q /own','pushd /own /private','cd -Q /own','cd /own /private','popd -Q','pushd +1','cd relative'];
 invalid.forEach((command,i)=>{it(`F45-R${i+1} unsupported cwd argv cannot grant successful effect`,()=>check(`cd /tmp; ${command}; rm -rf *`,STATE));it(`F45-SIMPLE${i+1} single absolute target and private cleanup remain`,()=>{check('cd /tmp; pushd /own; rm -rf *',SAFE);check('cd /tmp; cd /own; rm -rf *',SAFE);check('cd /own; /usr/bin/true; rm -rf .local/own-file',SAFE);});});
 it('F46-R format-bearing date capture saved and pipeline output is unknown',()=>{check('D=$(date +/tmp); rm -rf "$D"',TMP);check('date +/tmp > /own/date; D=$(cat /own/date); rm -rf "$D"',TMP);check('date +/tmp | xargs rm -rf',TMP);check('P=$(date +4242); kill "$P"',PID);});
 it('F46-SIMPLE recorded own output or literal replacement remain',()=>{check('date +/tmp; D=/own; rm -rf "$D"',SAFE);check('date +/tmp > /own/date; printf %s /own > /own/date; D=$(cat /own/date); rm -rf "$D"',SAFE);check('date; kill 4242',SAFE);});
 ['pushd /own','cd /own','popd'].forEach((command,i)=>{it(`F47-R${i+1} failed/unproved redirect gives no cwd execution grant`,()=>{check(`cd /tmp; ${command} 9<&- <&9; rm -rf *`,STATE);check(`cd /tmp; ${command} > /own/output; rm -rf *`,STATE);});it(`F47-SIMPLE${i+1} no redirected builtin or alternate parent effect needed`,()=>{check('cd /own; : > /own/output; rm -rf .local/own-file',SAFE);check('cd /tmp; cd /own; rm -rf *',SAFE);});});
});
